# Site settings
title: Remastered
header-img: img/blog_main_1.jpg
email: emilyabrahart@gmail.com
copyright_name: Emily Abrahart
description: "A journey from wannabe developer to the great beyond..."
baseurl: ""
url: "http://emilyabrahart.github.io"
twitter_username: emilyemilyjane
github_username:  emilyabrahart
facebook_username:  makersacademy
email_username:  emilyabrahart@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed, github-pages]
